name: Samsiky
favicon: null
layout_spectrum: 0.374155
typography_spectrum: 0.735642
title: Temporary Reality
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.263514
  lightness: 0.633446
  saturation: 0.391047
  rhythmicContrast: 0.283784
purpose:
  - name: null
    item: null
    url: null
