analytics: {}
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.263514
  lightness: 0.633446
  rhythmicContrast: 0.283784
  saturation: 0.391047
cta: {}
layout_spectrum: 0.374155
name: Samsiky
opengraph: {}
purpose: {}
typography_spectrum: 0.735642
